d/init: Reformat the case statement

diff --git a/debian/init b/debian/init
--- a/debian/init
+++ b/debian/init
@@ -36,33 +36,37 @@ fi
 
 case "$1" in
     start)
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
-	case "$?" in
-		0) # daemon successfully started
-			;;
-	        1) # daemon already running
-		        ;;
-		*) # daemon could not be started
-			echo "$DAEMON failed to start."
-			exit 1
-			;;
-	esac
-	;;
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
+        case "$?" in
+            0) # daemon successfully started
+                ;;
+            1) # daemon already running
+                ;;
+            *) # daemon could not be started
+                echo "$DAEMON failed to start."
+                exit 1
+                ;;
+        esac
+        ;;
+
     stop)
-	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --remove-pidfile --exec $DAEMON
-	rm -f /var/run/chrony-ppp-up
-	;;
+        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --remove-pidfile --exec $DAEMON
+        rm -f /var/run/chrony-ppp-up
+        ;;
+
     restart|force-reload)
         $0 stop
         $0 start
         ;;
+
     status)
-	status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
-	;;
+        status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
+        ;;
+
     *)
-	echo "Usage: /etc/init.d/chrony {start|stop|restart|force-reload|status}"
-	exit 1
-	;;
+        echo "Usage: /etc/init.d/chrony {start|stop|restart|force-reload|status}"
+        exit 1
+        ;;
 esac
 
 exit 0
